<a href="https://colab.research.google.com/github/MAYANKTIGER/ANN-stock-price-/blob/master/svm_knn_bnk_sub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import sklearn 
import seaborn as sns

In [7]:
from google.colab import files
uploaded = files.upload()
print(uploaded)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [8]:

data = pd.read_excel(uploaded['Marketing Campaign Result Prediction.csv'])

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['y'] = le.fit_transform(data['y'])

In [10]:
data.columns=data.columns.str.replace('[#,@,&,.,_]','')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [11]:
data.head(2)

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   

  month dayofweek  ...  campaign  pdays  previous     poutcome empvarrate  \
0   may       mon  ...         1    999         0  nonexistent        1.1   
1   may       mon  ...         1    999         0  nonexistent        1.1   

   conspriceidx  consconfidx  euribor3m  nremployed  y  
0        93.994        -36.4      4.857      5191.0  0  
1        93.994        -36.4      4.857      5191.0  0  

[2 rows x 21 columns]

In [12]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'dayofweek', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'empvarrate', 'conspriceidx', 'consconfidx',
       'euribor3m', 'nremployed', 'y'],
      dtype='object')

In [13]:
data['education']=np.where(data['education'] =='basic.9y', 'Basic', data['education'])
data['education']=np.where(data['education'] =='basic.6y', 'Basic', data['education'])
data['education']=np.where(data['education'] =='basic.4y', 'Basic', data['education'])

In [14]:
cat_vars=['job','marital','education','default','housing','loan','contact','month','dayofweek','poutcome']
for var in cat_vars:
    
    cat_list = pd.get_dummies(data[var], prefix=var)
    data1=data.join(cat_list)
    data=data1

In [15]:
cat_vars=['job','marital','education','default','housing','loan','contact','month','dayofweek','poutcome']
data_vars=data.columns.values.tolist()
to_keep=[i for i in data_vars if i not in cat_vars]

In [16]:
data_final=data[to_keep]
data_final.columns.values

array(['age', 'duration', 'campaign', 'pdays', 'previous', 'empvarrate',
       'conspriceidx', 'consconfidx', 'euribor3m', 'nremployed', 'y',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_Basic', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_no',
       'default_unknown', 'default_yes', 'housing_no', 'housing_unknown',
       'housing_yes', 'loan_no', 'loan_unknown', 'loan_yes',
       'contact_cellular', 'contact_telephone', 'month_apr', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'dayofweek_fri',
       '

In [17]:
data_final

age  duration  campaign  pdays  previous  empvarrate  conspriceidx  \
0       56       261         1    999         0         1.1        93.994   
1       57       149         1    999         0         1.1        93.994   
2       37       226         1    999         0         1.1        93.994   
3       40       151         1    999         0         1.1        93.994   
4       56       307         1    999         0         1.1        93.994   
...    ...       ...       ...    ...       ...         ...           ...   
41183   73       334         1    999         0        -1.1        94.767   
41184   46       383         1    999         0        -1.1        94.767   
41185   56       189         2    999         0        -1.1        94.767   
41186   44       442         1    999         0        -1.1        94.767   
41187   74       239         3    999         1        -1.1        94.767   

       consconfidx  euribor3m  nremployed  ...  month_oct  month_sep  \
0            -36.4      4.857      5191.0  ...          0          0   
1            -36.4      4.857      5191.0  ...          0          0   
2            -36.4      4.857      5191.0  ...          0          0   
3            -36.4      4.857      5191.0  ...          0          0   
4            -36.4      4.857      5191.0  ...          0          0   
...            ...        ...         ...  ...        ...        ...   
41183        -50.8      1.028      4963.6  ...          0          0   
41184        -50.8      1.028      4963.6  ...          0          0   
41185        -50.8      1.028      4963.6  ...          0          0   
41186        -50.8      1.028      4963.6  ...          0          0   
41187        -50.8      1.028      4963.6  ...          0          0   

       dayofweek_fri  dayofweek_mon  dayofweek_thu  dayofweek_tue  \
0                  0              1              0              0   
1                  0              1              0              0   
2                  0              1              0              0   
3                  0              1              0              0   
4                  0              1              0              0   
...              ...            ...            ...            ...   
41183              1              0              0              0   
41184              1              0              0              0   
41185              1              0              0              0   
41186              1              0              0              0   
41187              1              0              0              0   

       dayofweek_wed  poutcome_failure  poutcome_nonexistent  poutcome_success  
0                  0                 0                     1                 0  
1                  0                 0                     1                 0  
2                  0                 0                     1                 0  
3                  0                 0                     1                 0  
4                  0                 0                     1                 0  
...              ...               ...                   ...               ...  
41183              0                 0                     1                 0  
41184              0                 0                     1                 0  
41185              0                 0                     1                 0  
41186              0                 0                     1                 0  
41187              0                 1                     0                 0  

[41188 rows x 62 columns]

In [18]:
X = data_final.loc[:, data_final.columns != 'y']
y = data_final.loc[:, data_final.columns == 'y']

In [19]:
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [20]:
os = SMOTE(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


In [21]:
os_data_X,os_data_y=os.fit_resample(X_train, y_train)
#smote model fited on train data set 

In [22]:
os_data_Xtest,os_data_ytest=os.fit_resample(X_test, y_test)
#smote model fited on train data set 

In [23]:
from sklearn.svm import SVC


In [24]:
sv_rbf = SVC()

In [25]:
sv_rbf.fit(os_data_X, os_data_y) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [26]:
sv_rbf.score(os_data_Xtest,os_data_ytest )

0.8518096453642082

In [27]:
y_pred = sv_rbf.predict(os_data_Xtest)

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(os_data_ytest, y_pred)
print(confusion_matrix)

[[9219 1750]
 [1501 9468]]


In [30]:
from sklearn.metrics import classification_report
print(classification_report(os_data_ytest, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85     10969
           1       0.84      0.86      0.85     10969

    accuracy                           0.85     21938
   macro avg       0.85      0.85      0.85     21938
weighted avg       0.85      0.85      0.85     21938



clear data imbalance and predicted with SVM and got a better accuracy 

In [18]:
# data split  using iloc slicer 

In [19]:
x = data_final.loc[:, data_final.columns != 'y']
y = data_final.loc[:, data_final.columns == 'y']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# Train Support vector Model 

In [21]:
from sklearn.svm import SVC


In [22]:
sv_rbf = SVC()

In [23]:
sv_rbf.fit(X_train, y_train) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

# our model is ready to test and predict 

In [24]:
sv_rbf.score(X_test, y_test)

0.8914785142024764

In [25]:
y_pred = sv_rbf.predict(X_test)

In [26]:
sv_linear = SVC(kernel='linear')
sv_linear.fit(X_train, y_train) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [27]:
sv_linear.score(X_test, y_test)

0.8673221655741685

# comparision using confusion matrix 

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[7141  114]
 [ 780  203]]


In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94      7255
           1       0.64      0.21      0.31       983

    accuracy                           0.89      8238
   macro avg       0.77      0.60      0.63      8238
weighted avg       0.87      0.89      0.87      8238



# Train Model using KNN 

In [30]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [31]:
classifier.score(X_test, y_test)

0.894634620053411

In [32]:
y_predict = classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_predict)
print(confusion_matrix)

[[6908  347]
 [ 521  462]]


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      7255
           1       0.57      0.47      0.52       983

    accuracy                           0.89      8238
   macro avg       0.75      0.71      0.73      8238
weighted avg       0.89      0.89      0.89      8238



In [35]:
# KNN 